### ISSUE TITLE
US or GB

### ISSUE THREAD

**Issue by thewchan** [robinwhittleton/e-w-hornung_a-thief-in-the-night#2]
There is a lot of British spelling even though the `xml:lang` is `en-US`; I checked a lot of these spelling variant like "offence/offense", "jeweller/jeweler", I wonder if we should either change the tag to `en-GB` or switch the spelling? Although I suppose keeping it as is is fine as well, since these British spellings mostly show up in the M-W?

**Comment by thewchan** [comment]
Other more egregious British spelling like "despatch/dispatch"

**Comment by thewchan** [comment]
Another one like theater/theatre, criticize/criticise

**Comment by thewchan** [comment]
practised/practiced

**Comment by robinwhittleton** [comment]
There’s a load of USisms though, like `color`, `behavior`, etc. This is somewhat normal for books of this age, and typically we don’t adjust them.

**Comment by thewchan** [comment]
Sounds good to me then, just checking
