### ISSUE TITLE
bête noir

### ISSUE THREAD

**Issue by thewchan** [robinwhittleton/e-w-hornung_a-thief-in-the-night#3]
Ch1 ln 86

bête noir <- this seems to be a misspelling of bête noire. If so, it should not need italics as it appears in the M-W.

**Comment by robinwhittleton** [comment]
Good call, I was mildly surprised that `bête noir` wasn’t in MW but didn’t think to check if that was a misspelling.

Fixed in https://github.com/robinwhittleton/e-w-hornung_a-thief-in-the-night/commit/926ab0115c5031c48133a8d3643bbdda8a2b7389.
